update .gitlab-ci.yml and every-crate so every-crate is parallelized across all runners

diff --git a/maint/every-crate b/maint/every-crate
--- a/maint/every-crate
+++ b/maint/every-crate
@@ -6,18 +6,58 @@ set -euo pipefail
 
 : "${CARGO:=cargo}"
 
+NUM_CHUNKS=1
+CHUNK_N=1
+ 
+mapfile -t CRATES < <( maint/list_crates --all )
+NUM_CRATES=${#CRATES[@]}
+
+OPTS=":c:n:"
+
+while getopts ${OPTS} opt; do
+    case ${opt} in
+        c) 
+            if ! [[ "${OPTARG}" =~ ^[0-9]+$ ]]
+                then
+                    echo "Argument of -c must be a non-negative integer."
+                    exit 1
+            else 
+                CHUNK_N=$((CHUNK_N+${OPTARG}))
+            fi
+            ;;
+        n)
+            if ! [[ "${OPTARG}" =~ ^[0-9]+$ ]]
+                then
+                    echo "Argument of -n must be a positive integer."
+                    exit 1
+            else 
+                NUM_CHUNKS=${OPTARG}
+            fi
+            ;;
+        :)
+            echo "Option -${OPTARG} requires an argument."  
+            ;;
+        ?)
+            echo "Invalid option: ${OPTARG}."
+            exit 1
+            ;;
+    esac
+done
+
+if [[ $CHUNK_N -gt $NUM_CHUNKS ]]
+    then
+        echo "The chunk number (-c) must be less than or equal to the number of chunks (-n)."
+        exit 1
+fi  
+
 x () {
     echo ": $*"
     "$@"
 }
 
-export -f x
-
-test_crate () {
-    echo ==================== "$1" ====================
-    x cargo test -p "$1" --all-targets 
-}
-
-export -f test_crate
-
-./maint/list_crates --all | parallel --jobs "$1" -N1 -m test_crate
+for i in `seq $CHUNK_N $NUM_CHUNKS $NUM_CRATES`; do
+    echo ==================== "${CRATES[i]}" ====================
+    # allow $CARGO to contain multiple words
+    # shellcheck disable=SC20086
+    x $CARGO test -p "${CRATES[i]}" --all-targets 
+done
